# Site
name: 'Olcay SOYUHAN'
description: 'Veri bilimi, pazarlama vb. konularda içerikler.'
logo: ''
favicon: ''
baseurl: ''
disqus: 'olcay-s'
email: 'f/xeoqojgj'
google_verify: '04jnirQhgDnZjZjWk0IfPIL1vxKhksIxlMG7T_dxdtQ'
lang: tr-TR

# Google Analytics key, leave blank to ignore
google_analytics_key: 'G-NGWN492CY9'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    olcay:
      name:           Olcay SOYUHAN
      site:           
      avatar:         
      bio:            "    Ben Olcay Soyuhan, perakende sektöründe 20 yılı aşkın deneyime sahip bir profesyonelim. 
  Bu süreçte satış stratejileri geliştirme, mağaza yönetimi ve stok takibi gibi birçok alanda önemli tecrübeler edindim ve 
  sektörün dinamiklerine hakim olarak başarımı her geçen gün artırmayı hedefledim.

      Perakende yolculuğum 2003 yılında GİMA T.A.Ş.'de mağaza satış danışmanı olarak başladı. 
  Ardından, CarrefourSA, Metro Cash&Carry ve Migros T.A.Ş. gibi sektördeki önemli markalarda farklı görevlerde bulunarak 
  müşteri memnuniyetini sağlamaya ve operasyonel verimliliği artırmaya yönelik pek çok projede yer aldım.

      Eğitim hayatımda da sürekli gelişime inandım ve bu doğrultuda işletme ve pazarlama yönetimi üzerine derinleştim. 
  Halen Anadolu Üniversitesi’nde Pazarlama Yönetimi üzerine yüksek lisans yaparak bilgi ve becerilerimi güncel tutuyorum. 
  Ayrıca, teknolojiye olan ilgim sayesinde HTML, CSS, Python ve SQL gibi yazılım dillerini öğrenerek veri analizi ve yazılım geliştirme 
  konularında da kendimi geliştirmekteyim.

      Sayfamda, teknoloji, yazılım, perakende sektörü ve kişisel gelişim üzerine düşüncelerimi, öğrendiklerimi ve deneyimlerimi paylaşmayı amaçlıyorum. 
  Herhangi bir konuda sorularınız veya yorumlarınız varsa, bana her zaman ulaşabilirsiniz!
"
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: olcay
      avatar: 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]