# Site
name: 'Olcay SOYUHAN'
description: 'Veri bilimi, pazarlama vb. konularda içerikler.'
logo: ''
favicon: ''
baseurl: ''
disqus: 'olcay-s'
email: 'f/xeoqojgj'
google_verify: '04jnirQhgDnZjZjWk0IfPIL1vxKhksIxlMG7T_dxdtQ'
lang: tr-TR

# Google Analytics key, leave blank to ignore
google_analytics_key: 'G-NGWN492CY9'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    olcay:
      name:           Olcay SOYUHAN
      site:           
      avatar:         
      bio:            "Olcay SOYUHAN Anadolu Üniversitesi İşletme Fakültesini bitirdikten sonra aynı üniversitede Pazarlama Yönetimi Yüksek Lisansı yapmaktadır. İstanbul Teknik Üniversitesi tarafından düzenlenen Veri Bilimi Uzmnalığı Sertifika Programını başarıyla tamamlayarak farklı eğitimler neticesi elde ettiği sertifikalarına bir yenisini eklemiştir."
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: olcay
      avatar: 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]